### ISSUE TITLE
未加载过的页面无法改变数据问题

### ISSUE THREAD

**Issue by yuanyang749** [tanweijiu/EBus-JS#1]
现象是我在index1页面添加一方法改变index1页面某个数据，同时通知index2页面的数据也要发生改变，此时index2页面是没有打开过的，进到index2页面数据没有发生变化；这是我再回到index1，然后做同样的操作，这时index2的数据也改变了，请问此插件就是这样还是bug问题？

**Comment by tanweijiu** [comment]
@demi520 这个是合理的，事件通知机制的作用是跨页面跨线程通知...你提出的这个页面还没有运行，试问又如何响应通知呢？按你的这种情况，【建议：在index1使用postSticky（这个跟post的区别在于会存储最新的一份的eventData数据），可以在index2加载的时候（比如onload）使用getSticky主动的获取eventData】。当初在设计接口的时候，考虑到了其他的情况，故而没有在注册事件的时候判断是否存在sticky，而是新增getSticky可以人为手动主动地控制

**Comment by yuanyang749** [comment]
@tanweijiu 谢谢你的详细解答，我试试postSticky
